[{'slug': 1723, 'bonusesCreditTotal': 0, 'bonusesChargeTotal': 0, 'id': 1723, 'number': '1723',
  'orderType': 'eshop-individual', 'orderMethod': 'manual', 'privilegeType': 'none', 'countryIso': 'RU',
  'createdAt': '2021-11-29 00:30:04', 'statusUpdatedAt': '2021-11-29 00:32:13', 'summ': 70709, 'totalSumm': 71499,
  'prepaySum': 0, 'purchaseSumm': 0, 'markDatetime': '2021-11-29 00:30:04', 'firstName': 'Andrei test',
  'phone': '89101558161', 'email': '', 'call': False, 'expired': False, 'managerComment': '', 'managerId': 11,
  'customer': {'type': 'customer', 'id': 1106, 'isContact': False, 'createdAt': '2021-11-25 15:52:21', 'managerId': 11,
               'vip': False, 'bad': False, 'site': 'laitcom-ru',
               'contragent': {'contragentType': 'legal-entity', 'INN': '3664069397'}, 'tags': [], 'marginSumm': 142998,
               'totalSumm': 142998, 'averageSumm': 71499, 'ordersCount': 2, 'costSumm': 0, 'customFields': [],
               'personalDiscount': 25,
               'address': {'id': 540, 'countryIso': 'RU', 'region': 'Тульская область', 'regionId': 6, 'city': 'Тула',
                           'cityId': 4908, 'cityType': 'г.', 'text': 'Kalujskoe shosse, 1,'}, 'segments': [],
               'firstName': 'Andrei test', 'email': '',
               'phones': [{'number': '89991112233'}, {'number': '89101558161'}]},
  'contact': {'type': 'customer', 'id': 1106, 'isContact': False, 'createdAt': '2021-11-25 15:52:21', 'managerId': 11,
              'vip': False, 'bad': False, 'site': 'laitcom-ru',
              'contragent': {'contragentType': 'legal-entity', 'INN': '3664069397'}, 'tags': [], 'marginSumm': 142998,
              'totalSumm': 142998, 'averageSumm': 71499, 'ordersCount': 2, 'costSumm': 0, 'customFields': [],
              'personalDiscount': 25,
              'address': {'id': 540, 'countryIso': 'RU', 'region': 'Тульская область', 'regionId': 6, 'city': 'Тула',
                          'cityId': 4908, 'cityType': 'г.', 'text': 'Kalujskoe shosse, 1,'}, 'segments': [],
              'firstName': 'Andrei test', 'email': '',
              'phones': [{'number': '89991112233'}, {'number': '89101558161'}]},
  'contragent': {'contragentType': 'legal-entity', 'INN': '3664069397'},
  'delivery': {'code': 'd5dc972fe9', 'cost': 790, 'netCost': 0, 'date': '2021-11-26',
               'time': {'from': '17:00', 'to': '22:00'},
               'address': {'countryIso': 'RU', 'region': 'Тульская область', 'regionId': 6, 'city': 'Тула',
                           'cityId': 4908, 'cityType': 'г.', 'text': 'Kalujskoe shosse, 1,'}}, 'site': 'laitcom-ru',
  'status': 'send-to-delivery', 'items': [
        {'bonusesChargeTotal': 0, 'bonusesCreditTotal': 0, 'markingCodes': [], 'discounts': [], 'id': 3169,
         'priceType': {'code': 'base'}, 'initialPrice': 16990, 'discountTotal': 0,
         'prices': [{'price': 16990, 'quantity': 1}], 'vatRate': 'none', 'createdAt': '2021-11-29 00:30:04',
         'quantity': 1, 'status': 'otgruzhen', 'offer': {
            'displayName': 'Гирлянда Занавес 2 x 3 м Тепло-Белый с Мерцанием Каждого Диода 220В, 600 LED, Провод Черный Каучук, IP65',
            'id': 57444, 'externalId': '02cb8117-19ec-11e3-b8f3-0025909400bd',
            'xmlId': '02cb8117-19ec-11e3-b8f3-0025909400bd',
            'name': 'Гирлянда Занавес 2 x 3 м Тепло-Белый с Мерцанием Каждого Диода 220В, 600 LED, Провод Черный Каучук, IP65',
            'article': 'LL602ABL-1-2WW', 'vatRate': 'none',
            'properties': {'dlina': '42', 'sirina': '31', 'ves_kg': '2.54', 'vysota': '9', 'mercanie': 'Да',
                           'razmer_m': '2 x 3', 'zasita_ip': 'IP65', 'kod_tovara': '04-068', 'tip_provoda': 'Каучук',
                           'cvet_provoda': 'Черный', 'naprazenie_v': '220', 'cvet_svecenia': 'Тепло-Белый',
                           'dlina_setevogo_snura_m': '1,2', 'kolicestvo_svetodiodov': '600 led',
                           'kabel_pitania_v_komplekte': 'Да'}, 'unit': {'code': 'pc', 'name': 'Штука', 'sym': 'шт.'}},
         'properties': [], 'purchasePrice': 0},
        {'bonusesChargeTotal': 0, 'bonusesCreditTotal': 0, 'markingCodes': [], 'discounts': [], 'id': 3170,
         'priceType': {'code': 'base'}, 'initialPrice': 1590, 'discountTotal': 0,
         'prices': [{'price': 1590, 'quantity': 1}], 'vatRate': 'none', 'createdAt': '2021-11-29 00:30:04',
         'quantity': 1, 'status': 'otgruzhen',
         'offer': {'displayName': 'Гирлянда Нить 10м Белая 24В, 100 LED, Провод Прозрачный ПВХ, IP54', 'id': 56787,
                   'externalId': 'e008cbc9-367a-11e8-a21d-ac1f6b222f19',
                   'xmlId': 'e008cbc9-367a-11e8-a21d-ac1f6b222f19',
                   'name': 'Гирлянда Нить 10м Белая 24В, 100 LED, Провод Прозрачный ПВХ, IP54',
                   'article': 'PST100-10-1W', 'vatRate': 'none',
                   'properties': {'dlina': '9,9', 'sirina': '19,5', 'ves_kg': '0.387', 'vysota': '7,8',
                                  'mercanie': 'Нет', 'razmer_m': '10', 'zasita_ip': 'IP54', 'kod_tovara': '05-150',
                                  'mosnost_vt': '7', 'tip_provoda': 'ПВХ', 'cvet_provoda': 'Прозрачный',
                                  'naprazenie_v': '24', 'cvet_svecenia': 'Белый', 'vozmoznost_soedinenia': 'до 10 шт.',
                                  'vozmoznost_upravlenia': 'Нет', 'kolicestvo_svetodiodov': '100 led',
                                  'kabel_pitania_v_komplekte': 'Нет'},
                   'unit': {'code': 'pc', 'name': 'Штука', 'sym': 'шт.'}}, 'properties': [], 'purchasePrice': 0},
        {'bonusesChargeTotal': 0, 'bonusesCreditTotal': 0, 'markingCodes': [], 'discounts': [], 'id': 3171,
         'priceType': {'code': 'promo'}, 'initialPrice': 2290, 'discountTotal': 0,
         'prices': [{'price': 2290, 'quantity': 1}], 'vatRate': 'none', 'createdAt': '2021-11-29 00:30:04',
         'quantity': 1, 'status': 'otgruzhen', 'offer': {
            'displayName': 'Гирлянда Роса Конский Хвост 1,5м Розовая, 12В, 200 LED, Провод Прозрачный Проволока, IP67',
            'id': 58455, 'externalId': '2a0bd997-fb59-11e1-b458-000423d33392',
            'xmlId': '2a0bd997-fb59-11e1-b458-000423d33392',
            'name': 'Гирлянда Роса Конский Хвост 1,5м Розовая, 12В, 200 LED, Провод Прозрачный Проволока, IP67',
            'article': 'Branch 200-05-P', 'vatRate': 'none',
            'properties': {'dlina': '21', 'sirina': '11', 'ves_kg': '0.25', 'vysota': '7', 'razmer_m': '1.5',
                           'zasita_ip': 'IP67', 'kod_tovara': '08-036', 'mosnost_vt': '2', 'rasprodaza': 'Да',
                           'tip_provoda': 'Проволока', 'cvet_provoda': 'Прозрачный', 'naprazenie_v': '12',
                           'cvet_svecenia': 'Розовый', 'vozmoznost_soedinenia': 'нет', 'vozmoznost_upravlenia': 'нет',
                           'dlina_setevogo_snura_m': '1,5', 'kolicestvo_svetodiodov': '200 led'},
            'unit': {'code': 'pc', 'name': 'Штука', 'sym': 'шт.'}}, 'properties': [], 'purchasePrice': 0},
        {'bonusesChargeTotal': 0, 'bonusesCreditTotal': 0, 'markingCodes': [], 'discounts': [], 'id': 3172,
         'priceType': {'code': 'base'}, 'initialPrice': 159, 'discountTotal': 0,
         'prices': [{'price': 159, 'quantity': 1}], 'vatRate': 'none', 'createdAt': '2021-11-29 00:30:04',
         'quantity': 1, 'status': 'otgruzhen',
         'offer': {'displayName': 'Комплект подключения с 1 коннектором 24V, Длина 1м, Провод Черный ПВХ', 'id': 57814,
                   'externalId': '3101bfa7-126f-11e4-9a4a-0025909400bd',
                   'xmlId': '3101bfa7-126f-11e4-9a4a-0025909400bd',
                   'name': 'Комплект подключения с 1 коннектором 24V, Длина 1м, Провод Черный ПВХ',
                   'article': 'SLL1-11-1', 'vatRate': 'none',
                   'properties': {'dlina': '5', 'sirina': '10', 'ves_kg': '0.06', 'vysota': '10', 'razmer_m': '1',
                                  'zasita_ip': 'IP65', 'kod_tovara': '25-018', 'tip_provoda': 'ПВХ',
                                  'cvet_provoda': 'Черный', 'naprazenie_v': '24', 'cvet_svecenia': '0',
                                  'vozmoznost_soedinenia': 'Да'},
                   'unit': {'code': 'pc', 'name': 'Штука', 'sym': 'шт.'}}, 'properties': [], 'purchasePrice': 0},
        {'bonusesChargeTotal': 0, 'bonusesCreditTotal': 0, 'markingCodes': [], 'discounts': [], 'id': 3173,
         'priceType': {'code': 'base'}, 'initialPrice': 3490, 'discountTotal': 0,
         'prices': [{'price': 3490, 'quantity': 1}], 'vatRate': 'none', 'createdAt': '2021-11-29 00:30:04',
         'quantity': 1, 'status': 'otgruzhen',
         'offer': {'displayName': 'Светодиодная Гирлянда Роса 5м Разноцветная 24В, 10 LED, Провод Черный ПВХ, IP54',
                   'id': 56950, 'externalId': 'df170ae3-0b68-11ea-a250-ac1f6b222f19',
                   'xmlId': 'df170ae3-0b68-11ea-a250-ac1f6b222f19',
                   'name': 'Светодиодная Гирлянда Роса 5м Разноцветная 24В, 10 LED, Провод Черный ПВХ, IP54',
                   'article': 'BLL10R-11-1RGB', 'vatRate': 'none',
                   'properties': {'dlina': '25', 'sirina': '19,5', 'ves_kg': '0.83', 'vysota': '19,5', 'mercanie': 'Да',
                                  'zasita_ip': 'IP54', 'kod_tovara': '21-023', 'tip_provoda': 'ПВХ',
                                  'cvet_provoda': 'Черный', 'naprazenie_v': '24', 'cvet_svecenia': 'RGB',
                                  'diametr_sarika_mm': '10', 'vozmoznost_soedinenia': 'да',
                                  'vozmoznost_upravlenia': 'нет', 'dlina_setevogo_snura_m': '5',
                                  'kolicestvo_podvesov_st': '10', 'sag_mezdu_podvesami_sm': '50'},
                   'unit': {'code': 'pc', 'name': 'Штука', 'sym': 'шт.'}}, 'properties': [], 'purchasePrice': 0},
        {'bonusesChargeTotal': 0, 'bonusesCreditTotal': 0, 'markingCodes': [], 'discounts': [], 'id': 3174,
         'priceType': {'code': 'base'}, 'initialPrice': 12900, 'discountTotal': 0,
         'prices': [{'price': 12900, 'quantity': 1}], 'vatRate': 'none', 'createdAt': '2021-11-29 00:30:04',
         'quantity': 1, 'status': 'otgruzhen',
         'offer': {'displayName': 'Сетка Stylnet Прозрачная в Рулоне, Гибкий ПВХ, 10 x 1 м', 'id': 57505,
                   'externalId': 'c5f78944-aef5-11ea-a251-ac1f6b222f19',
                   'xmlId': 'c5f78944-aef5-11ea-a251-ac1f6b222f19',
                   'name': 'Сетка Stylnet Прозрачная в Рулоне, Гибкий ПВХ, 10 x 1 м', 'article': 'SDL1800-Tr',
                   'vatRate': 'none',
                   'properties': {'dlina': '100', 'sirina': '25', 'ves_kg': '9.91', 'vysota': '25', 'material': 'ПВХ',
                                  'razmer_m': '10 x 1', 'cvet_setki': 'Прозрачный', 'kod_tovara': '32-004'},
                   'unit': {'code': 'pc', 'name': 'Штука', 'sym': 'шт.'}}, 'properties': [], 'purchasePrice': 0},
        {'bonusesChargeTotal': 0, 'bonusesCreditTotal': 0, 'markingCodes': [], 'discounts': [], 'id': 3175,
         'priceType': {'code': 'base'}, 'initialPrice': 29900, 'discountTotal': 0,
         'prices': [{'price': 29900, 'quantity': 1}], 'vatRate': 'none', 'createdAt': '2021-11-29 00:30:04',
         'quantity': 1, 'status': 'otgruzhen', 'offer': {
            'displayName': 'Светодиодный Дюралайт Ø13 мм Желтый с Мерцанием Белого Диода, 36 LED/м, Свечение 360°, IP65, Бухта 100м',
            'id': 58183, 'externalId': '9201e68a-cf43-11eb-a268-ac1f6b222f19',
            'xmlId': '9201e68a-cf43-11eb-a268-ac1f6b222f19',
            'name': 'Светодиодный Дюралайт Ø13 мм Желтый с Мерцанием Белого Диода, 36 LED/м, Свечение 360°, IP65, Бухта 100м',
            'article': 'F3-H2-220V-BL-Y', 'vatRate': 'none',
            'properties': {'dlina': '22', 'sirina': '35', 'ves_kg': '16', 'vysota': '35', 'mercanie': 'Да',
                           'razmer_m': '100', 'zasita_ip': 'IP65', 'kod_tovara': '27-032', 'naprazenie_v': '220',
                           'cvet_svecenia': 'Желтый', 'kratnost_rezki_m': '2', 'svecenie_duralajta': '360°',
                           'vozmoznost_soedinenia': 'Да', 'vozmoznost_upravlenia': 'Нет',
                           'kabel_pitania_v_komplekte': 'Нет'}, 'unit': {'code': 'pc', 'name': 'Штука', 'sym': 'шт.'}},
         'properties': [], 'purchasePrice': 0},
        {'bonusesChargeTotal': 0, 'bonusesCreditTotal': 0, 'markingCodes': [], 'discounts': [], 'id': 3176,
         'priceType': {'code': 'base'}, 'initialPrice': 3390, 'discountTotal': 0,
         'prices': [{'price': 3390, 'quantity': 1}], 'vatRate': 'none', 'createdAt': '2021-11-29 00:30:04',
         'quantity': 1, 'status': 'otgruzhen',
         'offer': {'displayName': 'Светодиодная Снежинка Ø0,5м Тепло-Белая, Дюралайт на Металлическом Каркасе, IP54',
                   'id': 58315, 'externalId': '3d059dd2-96b6-11e6-aba5-0025909400bd',
                   'xmlId': '3d059dd2-96b6-11e6-aba5-0025909400bd',
                   'name': 'Светодиодная Снежинка Ø0,5м Тепло-Белая, Дюралайт на Металлическом Каркасе, IP54',
                   'article': 'LC-13041', 'vatRate': 'none',
                   'properties': {'dlina': '5', 'sirina': '61', 'ves_kg': '3', 'vysota': '61',
                                  'material': 'Дюралайт на Металическом Каркасе', 'mercanie': 'Нет', 'razmer_m': '0.5',
                                  'zasita_ip': 'IP54', 'kod_tovara': '13-041', 'mosnost_vt': '6,64',
                                  'tip_provoda': 'ПВХ', 'cvet_provoda': 'Белый', 'naprazenie_v': '220',
                                  'cvet_svecenia': 'Тепло-Белый', 'vozmoznost_soedinenia': 'Нет',
                                  'vozmoznost_upravlenia': 'Нет', 'dlina_setevogo_snura_m': '1,2'},
                   'unit': {'code': 'pc', 'name': 'Штука', 'sym': 'шт.'}}, 'properties': [], 'purchasePrice': 0}],
  'payments': {'1538': {'id': 1538, 'status': 'not-paid', 'type': 'b2b747b859', 'amount': 71499}}, 'fromApi': False,
  'weight': 33364, 'length': 0, 'width': 0, 'height': 0, 'shipmentStore': 'sklad1', 'shipmentDate': '2021-11-25',
  'shipped': False,
  'customFields': {'nasur': 'ipbogdv', 'a01f39e3c6': False, 'f1eb399029': False, 'soglashenie': 'ipbogdvs'}}]
